### ISSUE TITLE
Wrong GCC version in Windows toolchain name

### ISSUE THREAD

**Issue by matsobdev** [raspberrypi/pico-sdk-tools#6]
`riscv-toolchain-14-x64-win.zip` sounds like GCC 14.something.something, but in fact it is 13.2.0.

**Comment by will-v-pi** [comment]
Yes, that is correct - the Windows and x86_64 macOS toolchains are both taken from [here](https://www.embecosm.com/resources/tool-chain-downloads/#riscv-stable) and merely have our standard library copied in, so are GCC 13. We can remove the version from the filename if that is causing confusion.

**Comment by ndabas** [comment]
This will be fixed by #9:
- We will actually have GCC 14 in the build now.
- The build will detect the actual version of GCC and use that in the filename.
