### ISSUE TITLE
Windows RISC-V build can be fixed

### ISSUE THREAD

**Issue by ndabas** [raspberrypi/pico-sdk-tools#8]
I was looking at [this commit](https://github.com/raspberrypi/pico-sdk-tools/commit/63a716bf0c50a37883a740e1526fde65af083493) and the associated [Actions run](https://github.com/raspberrypi/pico-sdk-tools/actions/runs/10620457593/job/29440279667).

I saw something similar in my own experiments, and it sounds completely unrelated, but the issue can be fixed by setting `core.autocrlf` to `false` in the git config. On Windows the build.ps1 file is used to clone needed repos so you could likely just add `-c core.autocrlf=false` to the command line there:

https://github.com/raspberrypi/pico-sdk-tools/blob/178ced38c49a08c19f979c36d7fed27cb1420b7b/build.ps1#L180

(Or set it globally beforehand, it's a throwaway CI runner.)

**Comment by ndabas** [comment]
I actually [tried this](https://github.com/ndabas/pico-setup-windows/pull/35) and got it to work. The key elements are:
- The build uses file names that are too long for most tools on Windows to handle, so I had to `subst` the working directory to a drive to shorten the paths.
- MSYS2 makes deep copies instead of symlinks by default, but this can be easily changed with an environment variable. (`MSYS = "winsymlinks:nativestrict"`)
- I added the `base-devel` package to MSYS2 and cleaned up some of the others that were added in the test in this repo.

The last few commits of the PR linked above have the needed changes. Let me know if this is something you'd want and I can create a PR for it. I understand that there is a functional way to get a build for Windows already, but it's not 100% consistent with the build for Linux.

**Comment by will-v-pi** [comment]
Thanks - those do look like useful fixes, so if you could raise a PR that would be great

**Comment by will-v-pi** [comment]
I think a refactor would probably be better in a separate PR? Also, you could probably combine the `build_macos.sh` to make a single `build.sh` script that runs cross platform

**Comment by ndabas** [comment]
Okay, thanks, I've created a PR for this.
